# include controller and action
[route]
type = "resource" # reference: https://remix.run/docs/en/v1/guides/resource-routes

[request.GET]
controller = "api/user"
action = "list"

[request.POST]
controller = "api/user"
action = "update"
