# include controller and action
[request.GET]
controller = "index"
action = "show"
is_resource = false # whether this route is a resource route or not

[request.POST]
controller = "index"
action = "handlePost"
is_resource = false 
