# include controller and action
is_resource = false # whether this route is a resource route or not

[request.GET]
controller = "index"
action = "show"

[request.POST]
controller = "index"
action = "handlePost"
